version: '3.8'

services:
  personmanagement.api:
    image: ${DOCKER_REGISTRY-}personmanagementapi
    build:
      context: .
      dockerfile: src/PersonManagement.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PersonDb=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__Redis=${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - mssql
      - redis

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${DB_PORT}:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssqldata:/var/opt/mssql

  redis:
    image: "redis:7"
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mssqldata: